table AccType
	isHidden
	lineageTag: 7e57641d-ba27-4881-a075-0060d24ca9b2

	column Type
		dataType: string
		isHidden
		lineageTag: 9bf76ed0-c264-4f05-a44a-ee02daee342c
		summarizeBy: none
		sourceColumn: Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		isHidden
		lineageTag: 59784500-160e-40f9-bf43-de05aab97954
		summarizeBy: none
		sourceColumn: Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition AccType-cbcc89d5-e36b-40a8-a22b-25344245a77b = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcnR2DnJ1VtJRckxOzi/NKylWCEpNTs0sS0zKSVWK1QErCHCMRFYQkFgJkY0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Type = _t, Name = _t])
				in
				    Source

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

